name: Deploy container to Azure Function App

on:
  push:
    branches:
      - master  # Or your default branch name

env:
  AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Debug: List available secrets'
      run: |
        echo "Available secret names:"
        echo "${{ toJson(secrets) }}" | jq 'keys'
    
    - name: 'Debug: Check REGISTRY_USERNAME'
      run: |
        if [ -n "${{ secrets.REGISTRY_USERNAME }}" ]; then
          echo "REGISTRY_USERNAME is set"
        else
          echo "REGISTRY_USERNAME is not set"
        fi
    
    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: 'Build and push Docker image'
      run: |
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
        docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
    
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-container-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        image: ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
