name: Deploy container to Azure Function App

on:
  push:
    branches:
      - master  # Or your default branch name

env:
  AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Debug: Check required secrets'
      run: |
        echo "Checking required secrets:"
        if [ -n "${{ secrets.REGISTRY_USERNAME }}" ]; then 
          echo "REGISTRY_USERNAME is set"; 
        else 
          echo "REGISTRY_USERNAME is not set"; 
        fi
        
        if [ -n "${{ secrets.REGISTRY_PASSWORD }}" ]; then 
          echo "REGISTRY_PASSWORD is set"; 
        else 
          echo "REGISTRY_PASSWORD is not set"; 
        fi

        if [ -n "${{ secrets.CONTAINER_REGISTRY }}" ]; then 
          echo "CONTAINER_REGISTRY is set"; 
        else 
          echo "CONTAINER_REGISTRY is not set"; 
        fi

        if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then 
          echo "AZURE_CREDENTIALS is set"; 
        else 
          echo "AZURE_CREDENTIALS is not set"; 
        fi

        if [ -n "${{ secrets.AZURE_FUNCTIONAPP_NAME }}" ]; then 
          echo "AZURE_FUNCTIONAPP_NAME is set"; 
        else 
          echo "AZURE_FUNCTIONAPP_NAME is not set"; 
        fi
    
    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: 'Build and push Docker image'
      run: |
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
        docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
    
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-container-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        image: ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
